name: pos
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  page_transition: ^2.1.0
  nb_utils: ^7.0.6
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  barcode_widget: ^2.0.4
  syncfusion_flutter_charts: ^27.1.58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/icons/
